---
title: "Lab 03 - Nobel laureates"
author: "Tiffani Hill"
date: "01/30/2026"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(skimr)
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1
There are 935 observations, which as represented by rows. There are 26 variables.
```{r numberofobs-variables}
skim(nobel)

```

### Exercise 2
```{r new-data-frame}
nobel_living <- nobel %>% 
  filter(
  is.na(died_date),
  !is.na(country),
  gender != "org"
  )
nrow(nobel_living)



```

### Exercise 3
Most laureates who were foreign-born were not actually in the US. This is only true for economists.
```{r US-winners}
nobel_living <- nobel_living %>% 
  mutate(
    country_us = if_else(country == "USA", "USA", "Other"
  ))
nobel_living_science <- nobel_living %>% 
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

library(dplyr)
library(ggplot2)

ggplot(nobel_living_science, aes(x = born_country == "USA")) +
  geom_bar() +
  facet_wrap(~ category) + 
  coord_flip() +
  labs (
    x = "In the US when the prize was won",
    y = "Number of laureates",
    title = "Nobel Laureates in Science: US vs Other Countries"
  )
```

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
